[build-system]
requires = ["pip", "setuptools", "setuptools-scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "pymanopt"
dynamic = ["version"]
description = """\
  Toolbox for optimization on Riemannian manifolds with support for automatic \
  differentiation\
"""
authors = [
  {name = "Jamie Townsend"},
  {name = "Niklas Koep"},
  {name = "Sebastian Weichwald"},
]
readme = "README.md"
license = {text = "BSD 3-Clause License"}
requires-python = ">=3.8"
keywords = [
  "manifolds",
  "optimization",
  "automatic differentiation",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Mathematics",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "License :: OSI Approved :: BSD License",
  "Intended Audience :: Science/Research",
  "Development Status :: 5 - Production/Stable",
]
dependencies = [
  "numpy>=1.16.0",
  "scipy>=1.13.1",
  "pyparsing>=3.1.3",
]
[project.urls]
homepage = "https://pymanopt.org"

[project.optional-dependencies]
autograd = [
  "autograd>=1.2",
]
jax = [
  "jax>=0.2.0",
  "jaxlib",
]
tensorflow = [
  "tensorflow>=2.0.0",
]
torch = [
  "torch>=1.0.0",
]
backends = [
  "pymanopt[autograd,jax,tensorflow,torch]",
]
dev = [
  "black[jupyter]>=24.4.0",
  "flake8>=7.1.0",
  "flake8-bugbear>=24.4.2",
  "flake8-docstrings>=1.7.0",
  "flake8-pyproject>=1.2.3",
  "isort>=6.0.0",
  "matplotlib>=3.9.4",
  "pre-commit>=4.0.0",
  "pytest>=6.0.0",
  "pytest-cov>=6.0.0",
]
docs = [
  "docutils>=0.22",
  "ipykernel>=6.22.0",
  "myst-parser>=0.18.0",
  "nbsphinx>=0.10.3",
  "sphinx>=8.1.0",
  "sphinx_rtd_theme>=1.3.0",
  "sphinxcontrib-katex>=0.13.18",
]
ci = [
  "build>=1.2.0",
]
all = [
  "pymanopt[backends,dev]",
]
[tool.setuptools_scm]
write_to = "src/pymanopt/_version.py"

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*"]

[tool.black]
include = '\.py$'
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
filter_files = true
skip = [
  "src/pymanopt/_version.py",
]

[tool.flake8]
application_import_names = "pymanopt"
docstring-convention = "google"
exclude = [
  "examples/notebooks/*.py",
  "build"
]
ignore = ["B024", "B027", "B028", "D1", "E203", "E501", "W503"]
import_order_style = "pycharm"
max-line-length = 79
select = ["B", "B950", "C", "D", "E", "F", "W"]
per-file-ignores = [
  "examples/*:F811",
]
