__all__ = [
    "abs",
    "all",
    "allclose",
    "any",
    "arange",
    "arccos",
    "arccosh",
    "arctan",
    "arctanh",
    "argmin",
    "array",
    "array_as",
    "assert_almost_equal",
    "assert_allclose",
    "assert_array_almost_equal",
    "block",
    "conjugate",
    "cos",
    "diag",
    "diagonal",
    "exp",
    "expand_dims",
    "eye",
    "finfo",
    "float64",
    "get_backend",
    "hstack",
    "inf",
    "integer",
    "iscomplexobj",
    "isnan",
    "isrealobj",
    "linalg",
    "log",
    "logspace",
    "ndarray",
    "ndim",
    "newaxis",
    "to_backend",
    "ones",
    "pi",
    "prod",
    "random",
    "real",
    "seterr",
    "sin",
    "sinc",
    "sort",
    "spacing",
    "special",
    "sqrt",
    "squeeze",
    "sum",
    "tile",
    "trace",
    "transpose",
    "triu_indices",
    "tanh",
    "tensordot",
    "vstack",
    "where",
    "zeros",
    "zeros_like",
]


import importlib

from pymanopt.numerics.core import (
    abs,
    all,
    allclose,
    any,
    arange,
    arccos,
    arccosh,
    arctan,
    arctanh,
    argmin,
    array,
    assert_almost_equal,
    assert_allclose,
    assert_array_almost_equal,
    block,
    conjugate,
    cos,
    diag,
    diagonal,
    exp,
    expand_dims,
    eye,
    finfo,
    float64,
    hstack,
    inf,
    integer,
    iscomplexobj,
    isnan,
    isrealobj,
    log,
    logspace,
    ndarray,
    ndim,
    newaxis,
    ones,
    pi,
    prod,
    real,
    seterr,
    sin,
    sinc,
    sort,
    spacing,
    sqrt,
    squeeze,
    sum,
    tile,
    trace,
    transpose,
    triu_indices,
    tanh,
    tensordot,
    vstack,
    where,
    zeros,
    zeros_like,
)
from pymanopt.numerics import linalg, special
from pymanopt.numerics._backends.core import (
    array_as,
    get_backend,
    to_backend
)
from numpy import random

NUMERICS_SUPPORTED_BACKENDS = ["numpy", "pytorch"]


def register_backends():
    for backend in NUMERICS_SUPPORTED_BACKENDS:
        try:
            importlib.import_module(f"pymanopt.numerics._backends.{backend}")
        except ImportError:
            pass


register_backends()
