name: Run linting

on:
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: isort
        if: success() || failure()
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: isort --all-files

      - name: black
        if: success() || failure()
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: black --all-files

      - name: flake8
        if: success() || failure()
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: flake8 --all-files
